/// Every command the plugin exposes over the Tauri IPC.
///
/// `tauri-plugin` turns each name into an `allow-<name>` / `deny-<name>`
/// permission under `permissions/autogenerated/`, so a command added to
/// `src/commands.rs` but not here is unreachable from the frontend rather than
/// silently ungated.
const COMMANDS: &[&str] = &["status", "open_update"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
