//! `guest-js/bindings.ts` is generated from the Rust command signatures by
//! tauri-specta — and committed, so the JS package builds without a Rust
//! toolchain. This test is what keeps the committed copy honest: it exports the
//! bindings afresh and fails if they differ from what is in the tree.
//!
//! To regenerate after changing a command or a model:
//!
//! ```sh
//! UPDATE_BINDINGS=1 cargo test --test bindings
//! ```

use std::path::PathBuf;

use specta_typescript::Typescript;

#[test]
fn committed_bindings_match_the_rust_signatures() {
    let committed = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("guest-js/bindings.ts");
    let fresh =
        std::env::temp_dir().join(format!("webview-guard-bindings-{}.ts", std::process::id()));

    tauri_plugin_webview_guard::specta_builder::<tauri::test::MockRuntime>()
        .export(
            Typescript::default().header("// Generated by tauri-specta from src/commands.rs. Do not edit; run `UPDATE_BINDINGS=1 cargo test --test bindings`.\n"),
            &fresh,
        )
        .expect("export the bindings");
    let fresh_text = std::fs::read_to_string(&fresh).expect("read the fresh export");
    let _ = std::fs::remove_file(&fresh);

    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        std::fs::write(&committed, &fresh_text).expect("write guest-js/bindings.ts");
        return;
    }

    let committed_text = std::fs::read_to_string(&committed).unwrap_or_default();
    assert!(
        committed_text == fresh_text,
        "guest-js/bindings.ts is stale. Run `UPDATE_BINDINGS=1 cargo test --test bindings` and commit the result."
    );
}
