// Generated by tauri-specta from src/commands.rs. Do not edit; run `UPDATE_BINDINGS=1 cargo test --test bindings`.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  What the guard found at boot, and what it decided. */
	status: () => typedError<GuardStatus, WebviewGuardError>(__TAURI_INVOKE("plugin:webview-guard|status")),
	/**  Open the WebView provider's store listing. Android only. */
	openUpdate: () => typedError<UpdateOpened, WebviewGuardError>(__TAURI_INVOKE("plugin:webview-guard|open_update")),
};

/* Types */
/**  The engine family behind the app's WebView. */
export type EngineKind = 
/**  Android System WebView, Chrome/Trichrome, or an OEM Chromium build. */
"chromium" | 
/**  WKWebView. */
"webkit";

/**
 *  What the guard found at boot, and what it decided.
 * 
 *  Computed once, during plugin setup — before the first WebView exists — and
 *  never recomputed: a WebView provider update on Android kills the app's
 *  process, so a running process always has the engine it booted with.
 */
export type GuardStatus = {
	/**  Which platform this is. */
	platform: Platform,
	/**  Which engine family. */
	engine: EngineKind,
	/**
	 *  The version the device reported, verbatim: the provider's `versionName`
	 *  on Android (e.g. `109.0.5414.123`), the OS version on iOS (e.g. `16.3.1`).
	 *  `None` when the device reported nothing.
	 */
	installed: string | null,
	/**  The configured floor, as shown to the user: `111` or `16.4`. */
	required: string,
	/**
	 *  Android only: the package actually providing the WebView, as
	 *  `WebViewCompat.getCurrentWebViewPackage` returned it. Never assumed.
	 */
	providerPackage: string | null,
	/**
	 *  Android only: that package's user-visible label, e.g.
	 *  "Android System WebView". This is the name the dialog uses.
	 */
	providerLabel: string | null,
	/**  The decision. */
	verdict: Verdict,
};

/**  The mobile platform the guard ran on. */
export type Platform = 
/**  Android: the engine is whichever Chromium the WebView provider ships. */
"android" | 
/**  iOS: the engine is WKWebView, which ships with the OS. */
"ios";

/**  Which destination [`crate::WebviewGuard::open_update`] actually reached. */
export type StoreTarget = 
/**  `market://details?id=…` resolved: the Play Store app opened. */
"market" | 
/**
 *  No Play Store app resolved `market://`, so the
 *  `https://play.google.com/store/apps/details?id=…` fallback opened in a
 *  browser instead.
 */
"web";

/**  The result of [`crate::WebviewGuard::open_update`]. */
export type UpdateOpened = {
	/**  Where the user was sent. */
	target: StoreTarget,
	/**  The provider package whose listing was opened. */
	package: string,
};

/**  Whether the running engine clears the configured floor. */
export type Verdict = 
/**  At or above the floor. The app boots normally. */
"supported" | 
/**  Below the floor. The guard blocks the WebView and shows the native dialog. */
"below_floor" | 
/**
 *  The engine's version could not be read or parsed.
 * 
 *  The guard **lets the app boot** in this case and says so in the log and
 *  in [`crate::GuardStatus`]. Blocking would put an "update your WebView"
 *  dialog in front of a device that may be perfectly current — telling a
 *  user to fix something that is not broken is the same dead end as the
 *  white screen this plugin exists to replace.
 */
"unknown";

/**  A failed guard call. */
export type WebviewGuardError = 
/**
 *  This platform does not implement the capability at all.
 * 
 *  Returned on every desktop target for every call, and on iOS for
 *  [`crate::WebviewGuard::open_update`]. Never returned on a platform that
 *  does implement the call.
 */
{ kind: "unsupported"; 
/**  The platform the call ran on, e.g. `ios`, `macos`, `windows`. */
platform: string; 
/**  The call that was refused, e.g. `status`, `open_update`. */
capability: string; 
/**  Why, in a sentence a developer can act on. */
reason: string } | 
/**
 *  Neither the Play Store app nor any browser could open the provider's
 *  store listing. Android only.
 */
{ kind: "no_store_handler"; 
/**  The provider package whose listing was requested. */
package: string } | 
/**  The native side failed in a way it did not classify. */
{ kind: "native"; 
/**  The native command that failed. */
command: string; 
/**  The native side's own message. */
message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

